// <auto-generated />
namespace FIT5032_MyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202310101040422_removemodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
